import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#1B5E20',
  },
  header: {
    paddingHorizontal: 20,
    paddingTop: 50,
    paddingBottom: 20,
  },
  headerText: {
    color: 'white',
    fontSize: 28,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  content: {
    flex: 1,
    backgroundColor: '#fff',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingTop: 16,
  },
  card: {
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 24,
    marginBottom: 24,
    marginHorizontal: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  cardTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 16,
    textAlign: 'center',
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
    marginTop: 10,
    marginBottom: 16,
    textAlign: 'center',
  },
  hourlyRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 18,
    marginTop: 8,
    gap: 8,
  },
  hourlyItem: {
    alignItems: 'center',
    flex: 1,
    marginHorizontal: 2,
    minWidth: 70,
  },
  hourlyTemp: {
    fontSize: 15,
    color: '#333',
    marginTop: 2,
    fontWeight: 'bold',
  },
  hourlyRain: {
    fontSize: 13,
    color: '#1B5E20',
    marginTop: 2,
    fontWeight: 'bold',
  },
  hourlyTime: {
    fontSize: 12,
    color: '#888',
    marginTop: 2,
  },
  divider: {
    height: 1,
    backgroundColor: '#eee',
    marginVertical: 16,
  },
  weeklyContainer: {
    marginTop: 10,
  },
  weeklyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
    marginHorizontal: 2,
    justifyContent: 'space-between',
  },
  weeklyDay: {
    width: 70,
    fontSize: 15,
    color: '#333',
    fontWeight: 'bold',
    flexShrink: 0,
  },
  weeklyRain: {
    width: 40,
    fontSize: 14,
    color: '#1B5E20',
    textAlign: 'center',
    fontWeight: 'bold',
    flexShrink: 0,
  },
  weeklyTempHigh: {
    width: 50,
    fontSize: 14,
    color: '#333',
    textAlign: 'center',
    fontWeight: 'bold',
    flexShrink: 0,
  },
  weeklyTempLow: {
    width: 50,
    fontSize: 14,
    color: '#888',
    textAlign: 'center',
    fontWeight: 'bold',
    flexShrink: 0,
  },
  graphCard: {
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 20,
    marginHorizontal: 16,
    marginBottom: 32,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  graphHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  graphTitle: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#333',
  },
  graphSubtitle: {
    fontSize: 13,
    color: '#1B5E20',
    fontWeight: 'bold',
  },
  appBar: {
    width: '100%',
    height: 70,
    backgroundColor: '#1B5E20',
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: 20,
    marginBottom: 8,
  },
  appBarTitle: {
    color: 'white',
    fontSize: 28,
    fontWeight: 'bold',
    letterSpacing: 0.5,
  },
  graphLabelsRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 16,
    marginBottom: 8,
  },
  graphLabel: {
    fontSize: 15,
    color: '#333',
    fontWeight: 'bold',
  },
  greenDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#388e3c',
    marginRight: 6,
  },
  blueDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#1e88e5',
    marginRight: 6,
  },
}); 