#!/usr/bin/env bash
# Builds the release APK.
#
# Use this rather than calling gradlew directly, because of the ABI filter.
#
# The app ships four native ABIs by default, two of which (x86, x86_64) exist
# only for emulators — no phone will ever load them. With TensorFlow Lite now
# bundled they cost roughly 60 MB, close to half the APK.
#
# The obvious place to set this is android/gradle.properties, but android/ is
# generated by `expo prebuild` and is gitignored, so an edit there is silently
# discarded the next time a native dependency changes. That already happened
# once: a 71 MB build went back to 134 MB after a prebuild. Passing the
# property on the command line survives regeneration.
set -euo pipefail

cd "$(dirname "$0")/../android"

./gradlew assembleRelease \
  --no-daemon \
  --console=plain \
  -PreactNativeArchitectures=armeabi-v7a,arm64-v8a \
  "$@"

APK="app/build/outputs/apk/release/app-release.apk"
printf '\nAPK: %s (%.0f MB)\n' "$APK" "$(stat -c %s "$APK" | awk '{print $1/1048576}')"
